using System.Collections.Generic;
using UnityEngine;

namespace Qualium_Systems.WebXRPlugin.AR_Renderer.Scripts.BlendShapes
{
    public class ARBlendShapeController:MonoBehaviour
    {
        
        private FaceMesh faceMesh;

        #region Collections

        [SerializeField] private ARBlendShapeSettingsSO settings;
        private List<SkinnedMeshRenderer> skinnedMeshRenderers;
        private ARBlendShapeDictionary arBlendShapeDictionary = new ARBlendShapeDictionary();
        #endregion
        #region  Bones
        private Transform headBone;
        private Transform jawBone;
        #endregion
        #region Variables
        private float xRotationCloseJaw;
        private float xRotationOpenJaw;
        private bool isInit;
        private float baseDist;
        private int iterationCount;
        private bool isCalibrated;
        private bool isTracking;
        #endregion
        public FaceMesh FaceMesh
        {
            set { faceMesh = value; }
        }
        /// <summary>
        /// System initialization.
        /// </summary>
        /// <param name="blendShapesMapRef">The dictionary created to work in the inspector is needed for converting to a regular dictionary for gartering the names of blendshapes and internal enum . </param>
        /// <param name="jointsRef">The "JointPair" list does not contain information about all configured blendshapes (point settings, multiplier).</param>
        /// <param name="model">Reference to an object in the scene.</param>
        /// <param name="headBoneRef">(Optional) Needed to implement head rotation relative to the virtual face.</param>
        /// <param name="jawBoneRef">(Optional) On some models, the jaw is implemented as a separate object and does not change when changing the blendshape, in order to implement the opening of the jaw, in this case, you need to have a "bone" of the jaw.</param>
        public  void Init(List<ARBlendShapeDictionaryInspector> blendShapesMapRef,GameObject model,Transform headBoneRef=null,Transform jawBoneRef=null )
        {
            skinnedMeshRenderers = new List<SkinnedMeshRenderer>();
            skinnedMeshRenderers.AddRange(model.GetComponentsInChildren<SkinnedMeshRenderer>());
           
            arBlendShapeDictionary.ConvertDictionary(blendShapesMapRef);
            jawBone = jawBoneRef;
            headBone = headBoneRef;
            isInit = true;
        }

        public void StartTracking() => isTracking = true;
        

        public void StopTracking () => isTracking = false;
        
        public void JawSetup(float xRotationCloseJawRef,float xRotationOpenJawRef)
        {
            xRotationCloseJaw = xRotationCloseJawRef;
            xRotationOpenJaw = xRotationOpenJawRef;
        }
        public void Reset()
        {
            
            jawBone = null;
            headBone = null;
            isInit = false;
        }

        public void Calibrate()
        {
            isCalibrated = true;
        }
        /// <summary>
        /// Blendshape update.
        /// </summary>
        /// <param name="points">Points that are generated by a neural network for your face. It has the appearance of a canonical model of the face.</param>
        public  void UpdateBlendShapes(Vector3[] points)
        {
            if (!isInit||!isCalibrated||!isTracking)
            {
                return;
            }
            
            if (iterationCount < 5)
            {
                iterationCount++; return;}

            if (baseDist == 0)
            {
              
                baseDist = GetDist(points);
            }
            var currentDist = GetDist(points);
            var currentMag = faceMesh.transform.rotation.x;

           var rotDist = 1-(Mathf.Abs(currentMag) / 0.30f);
           var dist = currentDist / baseDist;
           dist = (dist*0.8f + rotDist) / 2;
           foreach (var jointPair in settings.JointPairs)
           {
              
               var flag = arBlendShapeDictionary.FaceMap.TryGetValue(jointPair.BlendShapesType, out var name);
               if(!flag) continue;

               var coefficient = jointPair.RecalculateCoefficient(points[jointPair.JointFirstIndex],
                   points[jointPair.JointSecondIndex]);
               coefficient *= dist;
              
               foreach (var skinnedMeshRenderer in skinnedMeshRenderers)
               {
                   if (skinnedMeshRenderer.sharedMesh.blendShapeCount == 0) continue;
                 
                       var index = skinnedMeshRenderer.sharedMesh.GetBlendShapeIndex(name);
                       if (index == -1) continue;
                       var fixedCoefficient = Mathf.Lerp(skinnedMeshRenderer.GetBlendShapeWeight(index), coefficient, 0.3f);
                       if (fixedCoefficient > 100) fixedCoefficient = 100;
                       if (fixedCoefficient < 0) fixedCoefficient = 0;
                       
                   skinnedMeshRenderer.SetBlendShapeWeight(index,fixedCoefficient);

               }

               if (jointPair.BlendShapesType == ARBlendShapesType.JawOpen)
               {
                   OpenJaw(coefficient);
               }
               RotateHead();
           }
        }

        private void RotateHead()
        {
            if (headBone == null) return;
            headBone.rotation = faceMesh.transform.rotation;
        }

        private void OpenJaw(float coefficient)
        {
            if (jawBone == null) return;
            if (xRotationOpenJaw == xRotationCloseJaw) return;
            var jawX = (xRotationOpenJaw / 100) * coefficient;
            var localEulerAngles = jawBone.localEulerAngles;
            localEulerAngles = new Vector3(jawX, localEulerAngles.y, localEulerAngles.z);
            jawBone.localEulerAngles = localEulerAngles;
        }
        /// <summary>
        /// Method for obtaining the "distortion" multiplier.
        /// </summary>
        /// <param name="points">Points that are generated by a neural network for your face. It has the appearance of a canonical model of the face.</param>
        /// <returns></returns>
        private float GetDist(Vector3[] points)
        {
            var faceHeight = Vector3.Distance(points[151], points[164]);
            var faceWeight = Vector3.Distance(points[23], points[253]);
            return faceHeight * faceWeight;
        }
      
        
    }
    
}